// Generated by softboot/export_web.py. Do not edit.
// Holds only mod_pr4x1s bytes; the stock OS comes from the user's own file.
export default {
 "name": "mod_pr4x1s",
 "stockName": "Main FW Rev 1.04",
 "version": "Main FW 1.04+pxs",
 "stockLen": 24912,
 "stockMd5": "e6959dcdeb645dde4be550e64fa2c698",
 "osLen": 24896,
 "resBase": 25088,
 "fileLen": 24896,
 "eeSumFrom": 1069,
 "eeSumAt": 8491,
 "patches": [
  [
   68,
   "MS4wNCtweHM="
  ],
  [
   528,
   "GmI="
  ],
  [
   6176,
   "B2Q="
  ],
  [
   7322,
   "62M="
  ],
  [
   7353,
   "rGQ="
  ],
  [
   8386,
   "jWQ="
  ],
  [
   8860,
   "zQBiAA=="
  ],
  [
   8875,
   "zQhiAA=="
  ],
  [
   23110,
   "BWU="
  ]
 ],
 "resident": "zVliEXNjGAbNWWIRdGPnzW5izTFjPoHDRmLNoVE6I2fLd8DNTWLAzW5iIfdlEfBlBgcaviAFIxMQ+MnNvwf1zTFj8cNGYs0UCM2/B8k6GWj+EMj+IMj+MMnNQAooB34PDw8P5g8hfSPvfjL+Zckh92U6T2h3IzokZ8t3KBM6NWG3KA2vdyM6NmHNKmMGAxg3OndozSpjOnhozSpjBgA6JGfLdygRrzIzYQYBOglny0coFQYCGBE6NGFPOlFouSAHOjNhtygBR3AjOgtnL+YQdyM6OWG3KCXtW/hlOjthPCAG7VM7YRgZOiRny3coEuUqO2G37VLhKAivMjlhdyN3yTo5YXcj3eU6OmHNAyDdfgDd4eYHT8s/RwQ6ImcFKAMPGPrmAYeHh7F3ybcgATx3I8kh92UR8GUBBwDtsBGyY+cRuGM69WW3KAbNgmMRv2PnOvNlhyHBY+9eI1bnOqpoD9g+is0UCDr0Zbc+PSgCPiHDYggTEoBTGFFoICAY/mUlIP5HDw8P5gMvxkXNYgh45gfGMc1iCD4tzWIIOvZlR+YHxjHNYgh45gg+ICgCPirDYgiQGk9oIP4Y8WUuGPJlIP7NY9Jj12PcY+Fj5mMgICAg/lBsYXn+UmVjIP5DbnQg/lVuZG/+UmVkb/6vMjVhzYwJIBDNhgkgCzqqaLcgBT4BMjVhw4YJOjVht8olGDokZ8t3IAo6NWH+Aig8wyUYOhlo/jAgMuU6NWH+AigaOjFotygjOjJotygdMjdhrzI2YT4CMjVhGBchOGE1ICY6NmEhN2G+IAjhrzI1YcMlGDoxaDI4YSE2YTR+PT4EKAI+AjIsZzo2YSE3Yb4gCzoxaMs/IThhvjADzSEb4cnN6h/NTWLAeuYfMjphOi1nh4eHsfaAMjlhPv8yO2HJrzInYTIzYSoAb+1bPGi37VJETSoCb+1bAG/tUss8yx3LPMsdt+1C2socKgJv5e1CIilhIgJv7UMrYesqPGjtsM3ZZSItYTpRaDIoYT4BMidhzcoc4SICb8nNhgnCJCc6GWj+EMIkJ80fZdrBC8NYBNE3yTonYbco+CEoYTpRaL4g781ACijqzVkKIi9h7UMxYSoAb+1SINkqKWHtUjjSKilh7VsrYRk4yOsqAm/tUjjA1c3ZZe1bLWHtUiCzKi9h7UsxYQnrKilh7UsrYe2w1SovYc3LZSovYe1bK2EZIgBv5esqL2HNy2Xh0dXNy2XhK9Eb7UsxYe1DK2HtuBPtUylhzdllIi1hOidhR+4DMidheMYDMjNhOlFoMjRht8kbt+1SGdAaTnd5EiMY8iopYe1LK2ERAAB7hl+CVyMLeLEg9evJ",
 "loaderHead": "8zHwfxHvgc2+ga/TjNOQIQAgEQEgAf9fd+2wPdOM05DtXs1QgQYQPgHTYM1QgSAIEPURCYLDSoE+AdNgzVCByjKAPgrTYAFAYdtiy0co+ttjC3ixIPPNUIE+LiACPlQyQ36v01ghLaERK6EBZjntsCF8ghEAAM1yga8yQH4yQX49MkJ+IQAA3SEogv0hAAABAAQ6QH7+GSADAfABEQAAfoNfPgCKVyMLeLEg8/0Z3X4AuyAG3X4BuigTOkJ+PCAGOkB+MkJ+OkF+PDJBft0j3SM6QH48MkB+/hogszpBfqfC8YAhXIIRAH8BIADtsMMAf/0iRH4hAH42ECMRPAAGEBoT/iA4BP5/OAI+P3cjEPA2kCM6RX7NXoE6RH7NXoE2ICM2YiM6Qn7NXoE2ICM2biM6QX7NXoE2ICM6BADNXoE6Q353Izb+EQB+zb6Bdhj9IQAA22LLf8AjfLUg9sn1Dw8PD81ngfHmD8aQJ85AJ3cjyX4jMkZ+PggyR3571vB63mXQOkZ+DzJGfjAE7aAYI04jfiPlR+YPxgIySH54Dw8PD+YPR2JrN+1COkh+TwYA7bDhOkd+PTJHfiDAGLQaE/7+yEfmYHgoCw6i7XD6y4HToRjq/hAgBD4BGAj+kDgE5g/2wA6i7XD65oHToBjPEG1vZF9wcjR4MXOQTG9hZGluZyBPUy4uLv4QbW9kX3ByNHgxczogbm+QY2FyZCBDUFUgcmVwbHn+0pgFmZGgqr1/nTpra4two/imOqR/lgnK95eX17ukDZmokQC3ONYNur6+dqP7ecHQkUNSwiHwZRHxZTYAAQ8Z7bAhQH8RQX82AAG/gO2wMQBiwwAA",
 "packedLen": 22549,
 "outMd5": "7f0cfc42d0ee251303ae3c83414a2132"
};
